### ISSUE TITLE
Steps to create a simple wall based on start & end points

### ISSUE THREAD

**Issue by vinnividivicci** [IfcOpenShell/wasm-preview#4]
Hello,

I'm working towards being able to create walls by simply clicking the start and end points of the centre line of the wall. I'm getting close but could use some advice. 

In order to calculate the corner vertices of the wall based off of the centre line, I'm using the [shapely](https://github.com/shapely/shapely) library:
```
# Calculate the corner points of the extrusion of the wall based on the start and end points of it's center line.
p1p2 = LineString([p1, p2])
left = p1p2.parallel_offset(thickness / 2, 'left')
right = p1p2.parallel_offset(thickness / 2, 'right')
p2L = left.boundary[1]
p2R = right.boundary[0]
p1L = left.boundary[0]
p1R = right.boundary[1]
```
I then use these corner points to create the outline of the extrusion:
```
point_list_extrusion_area = [(p1R.x, p1R.y, 0.0), (p2R.x, p2R.y, 0.0), (p2L.x, p2L.y, 0.0), (p1L.x, p1L.y, 0.0), (p1R.x, p1R.y, 0.0)]
```

My code creates walls and aims them in the right direction but it's not quite displaying right in OpenIFCViewer (and doesn't open in others:
![New Note](https://user-images.githubusercontent.com/591242/204415333-0351bc3f-0a46-41dc-8352-344947f07c04.jpeg)

As you can see, there's a gap in between the end of one wall and the start of another, even I expected them to be touching based on my inputs.

So two questions:

1. Can you see anything obvious I'm doing wrong in [my code](https://github.com/IfcOpenShell/wasm-preview/blob/25a161a9dd1e4fa285e82caed1e83d515703db56/examples/model.py#L100)?
2. Is there a simpler way to achieve what I'm doing (draw a wall based on start and end points) without using Shapely and only using IfcOpenShell?

**Comment by Moult** [comment]
The add_wall_representation can specify the length of the wall. The start of the wall is determined by the edit_object_placement of the wall and the end is determined by length plus the edit_object_placement rotation matrix.

**Comment by aothms** [comment]
> As you can see, there's a gap in between the end of one wall and the start of another, even I expected them to be touching based on my inputs.

I think it's because of the fact that you use p1 both as the polyline point as well as the translation component of the placement matrix of the extrusion. So p1 gets applied twice.

```
        polyline = self.create_ifcpolyline(self.model, [(p1[0], p1[1], 0.0), (p2[0], p2[1], 0.0)])
        axis_representation = self.model.createIfcShapeRepresentation(self.body, "Axis", "Curve2D", [polyline])
        extrusion_placement = self.create_ifcaxis2placement(self.model, (p1[0], p1[1], 0.0), (0.0, 0.0, 1.0), (1.0, 0.0, 0.0))
```

The idiomatic way in IFC to model as a wall. Is a **2d** polyline: (0, 0) -> (length, 0). And any other rotation/translation is made as part of the IfcWall.ObjectPlacement.

It would be very interesting to see what the code would look like making more use of the `ifcopenshell.api`. Especially in further scenarios it will be very helpful in creating/updating wall joins, openings, appending assets from libraries for e.g doors/windows.

@Moult if you have a minute, do you think you can provide a list of the api calls you think are relevant for this?

**Comment by aothms** [comment]
Edit: this is so awesome though. Question: @vinnividivicci do you have a reason why you seem to be working primarily as a python script and not in javascript using the pyodide proxy objects? I guess the more interactive it becomes the easier it is to just use JS?

**Comment by Moult** [comment]
This is a simple wall from 2 points:

```python
import numpy as np
import ifcopenshell.api.run as run

def create_2pt_wall(p1, p2, elevation, height, thickness, container, wall_type=None):
    wall = run("root.create_entity", model, ifc_class="IfcWall")
    length = float(np.linalg.norm(p2 - p1))
    representation = run("geometry.add_wall_representation", model, context=body, length=length, height=height, thickness=thickness)
    v = p2 - p1
    v /= float(np.linalg.norm(v))
    matrix = np.array([
        [v[0], -v[1], 0, p1[0]],
        [v[1], v[0], 0, p1[1]],
        [0, 0, 1, elevation],
        [0, 0, 0, 1],
    ])
    run("geometry.edit_object_placement", model, product=wall, matrix=matrix)
    run("geometry.assign_representation", model, product=wall, representation=representation)
    run("spatial.assign_container", model, relating_structure=container, product=wall)
    if wall_type:
        run("type.assign_type", model, related_object=wall, relating_type=wall_type)

# Example
create_2pt_wall(np.array([0., 0.]), np.array([1., 0.]), 0, 3., 0.2, storey)
create_2pt_wall(np.array([0., 0.]), np.array([1., 1.]), 0, 3., 0.2, storey)
create_2pt_wall(np.array([1., 1.]), np.array([-2., 2.]), 0, 3., 0.2, storey)
```

**Comment by Moult** [comment]
With a bit more work, the BlenderBIM Add-on code could be generalised into numpy functions to support mitred joints and other types of smart parametric connections in the API.

**Comment by vinnividivicci** [comment]
Thanks for the feedback guys! I've simplified the code down to use the run API. @aothms I think the reason I have it in Python is partly because I prefer python but also to show that python can be used and that the code can be made quite portable.

I've made further progress, but I have a glitch currently with walls only drawing properly when drawing from left to right 😆 . I have a feeling it has to do with the way the angle is being calculated. You can see the results if you run the draw_wall_on_click.html page. 

Anyways, I'll keep plugging away at it.

**Comment by aothms** [comment]
That's right actually, the get_angle() function returns the unsigned angle difference with (1 0). You can try the following code which constructs a matrix from the normalized direction vector p2 - p1 directly.

```
v = p2 - p1
v /= numpy.linalg.norm(v)
matrix = np.array([
    [v[0], v[1], 0, p1[0]],
    [-v[1], v[0], 0, p1[1]],
    [0, 0, 1, elevation],
    [0, 0, 0, 1],
])
```

**Comment by Moult** [comment]
Ah that'll teach me to copy paste from StackOverflow :)

Ahem. ** copy pastes from @aothms instead **

I've updated the code with @aothms 's much better solution :D

**Comment by aothms** [comment]
We should be copying only from ChatGPT ;)

![afbeelding](https://user-images.githubusercontent.com/1096535/206186461-7f5daf99-c56b-408b-a236-66503980199d.png)

**Comment by vinnividivicci** [comment]
Thanks for the input guys, I used that new code for the angle and it works well. 

I've merged the "completed" example into [draw_wall_on_click.html](https://github.com/IfcOpenShell/wasm-preview/blob/master/examples/draw_wall_on_click.html). 

The next step in my mind is to get ThreeJS to only load the new objects, right now it's reloading the entire updated IFC into a new scene so it gets progressively slower with each added object. I'm not sure how to do this yet so I'll have to read up on ThreeJS but if you have some pointers I would appreciate it.

**Comment by aothms** [comment]
This is already very cool. And I think from here on it will get progressively easier to add more existing blenderbim functionality. Like we can use the same raycaster to add windows to existing walls.

I think it only requires some light restructuring:

- Return wall in create_2pt_wall()
- Instead of iterator here https://github.com/IfcOpenShell/wasm-preview/blob/master/examples/draw_wall_on_click.html#L254 use ifcopenshell.geom.create_shape(settings, wall) on the returned wall object
- What's returned from create_shape() is then the equivalent of `obj` https://github.com/IfcOpenShell/wasm-preview/blob/master/examples/draw_wall_on_click.html#L106 so can be added to the current threejs scene.

Does that help?

**Comment by vinnividivicci** [comment]
It sure does help! Check out the updated example. Now it only adds the latest wall to the scene and doesn't reload the whole thing. Much more scalable this way. 

Where do we go from here? I have lots of ideas but want to get your thoughts.

**Comment by aothms** [comment]
Very cool! I would say we need to identify the minimal set of things to show the potential in order to get people inspired:

- A toolbar. E.g [select] [wall] [window]
- Handling selection and showing properties of selected walls
- Download IFC
- Maybe a project library and option to change wall types
- Maybe wall joins (I can help port the math from bpy to numpy)
- Maybe windows

I can definitely contribute a couple of these as well. Let me know.

Or anything else, just the bare minimum to highlight there is the possibility to do fairly advanced geometry and semantics based modelling.

And then later with the help of others:

- WebRTC collaborative editing!
- Draw slabs based on picked wall edges
- Many realtime threejs UI things:
  - show wall polyline before construction
  - grid
  - ...
- Snapping
- Building storeys or work planes

Curious to hear what your ideas are.

**Comment by vinnividivicci** [comment]
I was also thinking about a basic UI to:

- pick element being created
- adjust its basic parameters (width, height, diameter, etc)
- add/remove or switch building storeys
- add some MEP types (pipes and ducts, I have an MEP bias...)
- save the resulting IFC file

Is there an API equivalent to "geometry.add_wall_representation" but for Pipes & Ducts?

**Comment by aothms** [comment]
> Is there an API equivalent to "geometry.add_wall_representation" but for Pipes & Ducts?

I guess that would be `geometry.add_profile_representation` with a IfcCircleHollowProfileDef for example.

I think it would be a lot more complicated though than walls. Walls have the nice property to typically run from storey to storey so you can draw then as a 2d polyline. I guess ducts is a lot more complex. It definitely fits the bill for what I proposed earlier in "do fairly advanced geometry and semantics based modelling", but I'm a bit worried about what the UI would like like in terms of creating the duct axis.

> pick element being created

Yep, second on my list.

 > adjust its basic parameters (width, height, diameter, etc)

I think that roughly corresponds to "Maybe a project library and option to change wall types". So we agree there I think.

> add/remove or switch building storeys

Also on my list, but I guess it's also one of the things people can imagine being built later

> save the resulting IFC file

Cool, agree there.

**Comment by vinnividivicci** [comment]
Closing this issue since it's technically complete, [here's an example ](https://github.com/IfcOpenShell/wasm-preview/blob/master/examples/2_draw_wall_on_click.html) of drawing a wall based on two points.

I will come back here for ideas on what to work on next though 😄
