### ISSUE TITLE
C++ or Python to start a new app ?

### ISSUE THREAD

**Issue by cvoivret** [IfcOpenShell/wasm-preview#5]
Hi @vinnividivicci, I have developed a [ revit addin](https://github.com/cvoivret/Canopia_revit) check a french environmental regulation.
It rely on a lot of CSG and Revit platform is nice but it is a dead end for collaboration and openness but it was a good place to start.
I want to port my work on the IFCopenshell platform.
I think I'm able to code it in Python and C++ but I don't know which one to choose, and more crucially, I don't know which one will be easier to deploy ( both as a standalone software and as a online tool).
From my ifcnoob perspective, I think that C++ is the right choice to build a standalone desktop soft and port it to the browser trough wasm. 
For python i think the difficulty will be to build a standalone (py2exe like). For porting it to the browser the wasm-preview project seems promising.
IFC.js is a seducing approach but seems to presently lack a CSG library.
I'm conscious that I want both of each world but from your expert perspective, what is the best present path ?
Regards and thank for all your work.

**Comment by aothms** [comment]
If I can chime in here, one aspect missing in your overview is what language you feel comfortable working in. These days you have a lot of options to get things in the hands of end-users. You could use ifcopenshell-wasm or ifc.js in an electron app. Or you could Qt in C++ or Python. Or implement it as a plug-in in BlenderBIM or FreeCAD. But it is you who have to build, maintain and test this, if you do this in an environment that enables you to be productive, your end users will come and find you.

Regarding C++ and Python the main difference seems to be statically typed vs dynamically typed, interpreted vs compiled. I can offer some perspective on this wrt to the IFC schema. There are many current schemas (with sometimes minimal differences), supporting them all at the same time is a lot easier in Python with runtime attribute lookup as opposed to compile time static typing. Static typing in IFC can be frustrating. With large software libraries such as Open CASCADE compilation times can be frustrating. That's why we in the IfcOpenShell camp feel that Python (with extensive unit testing) allows us to be productive while leveraging all the C++ goodness through binary modules. But this is a personal choice.

**Comment by cvoivret** [comment]
Thanks a lot @aothms for sharing your thought.
I deeply appreciate your insight that will probably will save me a lot of time and headache ! 
Then, Python it will be... 
In this case, have you a preferred solution to distribute an software to non python user ( like an exe for window ) ?
For me, the short term goal is to distribute a software and in the long run maybe porting it in the browser.

**Comment by Moult** [comment]
@cvoivret if it is standalone pyinstaller has worked very well for me in the past. I use it to distribute IfcPatch, IfcDiff, etc.

You may also consider an add-on to Blender or FreeCAD.

**Comment by aothms** [comment]
Another option is to simply use an installer to distribute all the files and a python interpreter and then create a little launcher (a windows shortcut or equivalent on other OS'es).

**Comment by cvoivret** [comment]
Nice suggestions.
No excuse to build the app now, except for the Christmas holidays.
Enjoy the end of the year celebrations.
Cheers
Charles

Le ven. 16 déc. 2022 à 14:25, Thomas Krijnen ***@***.***> a
écrit :

**Comment by vinnividivicci** [comment]
@cvoivret I echo the comments of my colleagues and I would like to simply add that a common mistake in software engineering is to optimize first when really we should get the software going using the easiest language for us (in my case Python, C#, etc) and optimize the parts that need extreme speed later (C++). This is described quite well here: https://effectiviology.com/premature-optimization/

Glad to see your interest in IfcOpenShell WASM and welcome to the community 😺
